# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}" #mandatory
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
#clientSideOnly=true #optional - defaults to false if absent

[[mods]] #mandatory
modId="pythonmc" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="${mod_authors}" #optional
#displayTest="MATCH_VERSION" #optional

description='''PythonMC es un mod que integra Python en Minecraft, permitiendo crear bloques, scripts y nodos tipo Godot dentro del juego. Con él puedes controlar cámaras, personajes y construir mundos de manera programática.'''
 #mandatory

[[dependencies.pythonmc]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="${forge_version_range}" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.pythonmc]] #optional
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# Optional feature declaration
#[features.pythonmc]
#openGLVersion="[3.2,)"
